lib Libyang

  enum LYDANYDATAVALUETYPE
    LYD_ANYDATA_CONSTSTRING
    LYD_ANYDATA_STRING
    LYD_ANYDATA_JSON
    LYD_ANYDATA_JSOND
    LYD_ANYDATA_SXML
    LYD_ANYDATA_SXMLD
    LYD_ANYDATA_XML
    LYD_ANYDATA_DATATREE
    LYD_ANYDATA_LYB
    LYD_ANYDATA_LYBD
  end

end