lib Libyang

  enum LYDANYDATAVALUETYPE
    LYD_ANYDATA_CONSTSTRING
    LYD_ANYDATA_STRING
    LYD_ANYDATA_JSON
    LYD_ANYDATA_JSOND
    LYD_ANYDATA_SXML
    LYD_ANYDATA_SXMLD
    LYD_ANYDATA_XML
    LYD_ANYDATA_DATATREE
    LYD_ANYDATA_LYB
    LYD_ANYDATA_LYBD
  end

  enum LYDDUPLICATIONOPTIONS
    LYD_DUP_OPT_RECURSIVE
    LYD_DUP_OPT_NO_ATTR
    LYD_DUP_OPT_WITH_PARENTS
    LYD_DUP_OPT_WITH_KEYS
    LYD_DUP_OPT_WITH_WHEN
  end

end